version: '2'
services:
# laravel app
  app:
    container_name: laravel_app
    restart: always
    depends_on:
      - "database"
    build:
      context: ./
      dockerfile: development/app.dockerfile
#    開發方便用
#    volumes:
#      - ./.phpstorm.meta.php:/var/www/.phpstorm.meta.php
#      - ./_ide_helper.php:/var/www/_ide_helper.php
#      - ./composer.json:/var/www/composer.json
#      - ./composer.lock:/var/www/composer.lock
#      - ./package.json:/var/www/package.json
#      - ./package-lock.json:/var/www/package-lock.json
#      - ./app:/var/www/app
#      - ./config:/var/www/config
#      - ./database:/var/www/database
#      - ./public:/var/www/public
#      - ./resources:/var/www/resources
#      - ./routes:/var/www/routes
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

# The Web Server
  web:
    container_name: nginx_server
    depends_on:
      - "app"
    restart: always
    build:
      context: ./
      dockerfile: development/web.dockerfile
    volumes:
    - ./storage/logs/:/var/log/nginx
#    開發方便用
#    - ./public/:/var/www/public
    ports:
    - 8990:80
# The Database
  database:
    container_name: mysql_database
    image: mysql:5.7
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=user"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 8991:3306
    # phpmyadmin
  phpmyadmin:
      depends_on:
        - database
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '8080:80'
      environment:
        PMA_HOST: mysql_database
        MYSQL_ROOT_PASSWORD: root
volumes:
  dbdata:
